# Generated by Django 4.2.16 on 2024-11-28 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lido',
            name='highlight',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lido',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
