# Generated by Django 4.2.16 on 2024-11-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lidos', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lido',
            options={'ordering': ['name']},
        ),
    ]
