# Generated by Django 4.2.16 on 2024-12-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tip', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifesaver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
