# Generated by Django 4.2.16 on 2024-11-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_lidosuggestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LidoSuggestion',
            new_name='Suggestion',
        ),
    ]
